  - name: install jenkin's repo key 
    shell:
     cmd: wget -q -O - https://pkg.jenkins.io/debian-stable/jenkins.io.key | sudo apt-key add
    
  - name: add apt jenkins repo
    shell:
     cmd: echo deb https://pkg.jenkins.io/debian-stable binary/ > /etc/apt/sources.list.d/jenkins.list

  - name: Apt update
    apt:
     update_cache: yes

  - name: install packages 
    apt:
      name: ['openjdk-8-jre','ansible', 'jenkins']
      state: present

  - name: install AWS cli
    pip:
      name: awscli

  - name: add jenkins to group docker
    shell:
     cmd: usermod -a -G docker jenkins

  - name: Start service jenkins, if not started
    service:
     name: jenkins
     state: started
     enabled: yes