- name: install key GPG for docker
  shell:
    cmd: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -

- name: add docker repo
  shell:
    cmd: add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"

- name: apt update
  apt:
    update_cache: yes

- name: install docker
  apt:
    name: docker-ce
    state: present

- name: add user ubuntu to group docker
  shell:
    cmd: usermod -a -G docker ubuntu

- name: install pip 
  apt:
    name: python3-pip
    state: present

- name: install Python docker module
  pip:
    name: docker
